# Generated by Django 2.0 on 2018-03-18 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_callback_url', models.CharField(max_length=20, verbose_name='url_field')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'user_field',
                'db_table': 'merchant_store',
            },
            managers=[
                ('token', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='merchantinfo',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokenapi.MerchantStore'),
        ),
    ]
