# Generated by Django 2.0 on 2018-03-18 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0002_auto_20180318_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantinfo',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokenapi.MerchantStore'),
        ),
    ]
